[tool.poetry]
name = "gigatrader"
version = "0.1.0"
authors = ["Gigatrader Bot <bot@example.com>"]
description = "Automated trading platform scaffold for Alpaca equities and options"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
alpaca-py = "^0.12.0"
pydantic = "^1.10.9"
pyyaml = "^6.0"
streamlit = "^1.27.0"
numpy = "^1.26.0"
pandas = "^2.1.0"
typer = {extras = ["all"], version = "^0.9.0"}
orjson = "^3.9.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-asyncio = "^0.21.1"
ruff = "^0.1.6"
mypy = "^1.5.1"
pytest-cov = "^4.1.0"

[tool.poetry.scripts]
trade = "scripts.cli:app"

[tool.ruff]
select = ["E", "F", "I", "B", "UP", "RUF"]
ignore = []
line-length = 100

[tool.mypy]
python_version = "3.11"
strict = true

[tool.pytest.ini_options]
addopts = "-ra"
filterwarnings = ["ignore::DeprecationWarning"]

