name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # FastAPI testclient is included via fastapi/starlette; no server needed
      - name: Run tests
        env:
          # no Alpaca keys on CI; tests are designed to pass without them
          MOCK_MODE: "true"
        run: |
          python -m pytest -q
